import type { Metadata } from 'next';
import { Roboto } from 'next/font/google'; // Import Roboto font

import { Toaster } from '@/components/ui/toaster';
import './globals.css';

// Google font (Roboto)
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify the weights you want to use
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Chat֎Boat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.variable} antialiased
      bg-zinc-950 text-zinc-50 min-h-screen
      `}
      >
        <main className="flex flex-col min-h-screen">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
